<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseAppHost>true</UseAppHost>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>PlayniteLibraryApplication</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\WidgetApplicationRuntime\WidgetApplicationRuntime.csproj" />
    <ProjectReference Include="..\PlayniteLibraryWidget.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\src\WindowsAppLibraryProvider\*.cs"
             Exclude="..\..\..\src\WindowsAppLibraryProvider\AssemblyInfo.cs"
             Link="Backend\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
