<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>obj\Core\</BaseIntermediateOutputPath>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>GameLauncherWidget.Core</AssemblyName>
    <DefineConstants>$(DefineConstants);GAME_LAUNCHER_COMMUNITY_CORE</DefineConstants>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\WidgetSdk\WidgetSdk.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="*.cs" Exclude="AssemblyInfo.cs" />
    <Compile Include="Core\AssemblyInfo.cs" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
