<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\WidgetSdk\WidgetSdk.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Application\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="manifest.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="community-manifest.json" />
    <None Include="styles\default.gbss" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
