<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\WidgetStyling\WidgetStyling.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\..\src\PlatformSettings\Themes\builtin-cool-slate\theme.gbss"
             Link="Themes\builtin-cool-slate.gbss"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
