using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Controls.Primitives;
using Microsoft.UI.Xaml.Input;
using Microsoft.UI.Xaml.Media.Imaging;
using WidgetRail.OverlayFrontend.WinUI.Presentation;
using WidgetRail.PlatformSettings;
using WidgetRail.WidgetBridge;
using WidgetRail.WidgetPresentationSession;
using WidgetRail.WidgetProtocol;
using WidgetRail.WidgetSdk;

namespace WidgetRail.OverlayFrontend.WinUI.Validation;

internal sealed partial class WidgetStylesValidationPage
{
    private async Task PlayniteProductionLayoutAsync(string path)
    {
        // Generated by PlayniteLibraryNativeLayoutFixtureTests using the actual
        // widget presenter + platform/package WRSS, not a parallel fixture UI.
        using var file = JsonDocument.Parse(await File.ReadAllBytesAsync(path));
        var snapshot = SnapshotJson.Deserialize(System.Text.Encoding.UTF8.GetBytes(file.RootElement.GetProperty("snapshot").GetRawText()));
        var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
        options.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
        var styles = file.RootElement.GetProperty("renderStyles").Deserialize<Dictionary<string, BridgeNodeRenderStyles>>(options)!;
        var scale = XamlRoot.RasterizationScale;
        App.Window.AppWindow.Resize(new((int)(1160 * scale), (int)(860 * scale)));
        presenter.ApplyAppearance(AppearanceSettings.Default with { Motion = MotionPreference.Reduced }, false);
        presenter.ResolveArtworkAsync = (_, _) => Task.FromResult<WidgetEncodedArtwork?>(new(WidgetArtworkContentType.Png,
            Convert.FromBase64String("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jq1sAAAAASUVORK5CYII=")));
        presenter.Width = 1000; presenter.Height = 600;
        var descriptor = new BridgeWidgetDescriptor { Id = "playnite.layout", Name = "Production Playnite layout",
            InstanceId = snapshot.WidgetInstanceId, RuntimeGeneration = "production-fixture", PresentationGeneration = "production-fixture",
            Icon = WidgetGlyph.Play, PackageContentDigest = string.Empty };
        presenter.Apply(new(new(descriptor.Id, descriptor.RuntimeGeneration, descriptor.PresentationGeneration, 1,
            descriptor.InstanceId, snapshot.Sequence, snapshot.ActiveInputScopeId), descriptor, snapshot, styles));
        const string prefix = "Widget.playnite-library.details.";
        await Wait(() => Find<WidgetArtworkView>(prefix + "poster") is { Source: BitmapSource { PixelWidth: > 0 } });
        var scroll = Find<ScrollViewer>("Widget.playnite-library.details.scroll")!;
        var poster = Find<WidgetArtworkView>(prefix + "poster")!;
        var play = Find<Button>(prefix + "play")!;
        play.Focus(FocusState.Keyboard);
        await Task.Delay(150);
        Check(scroll.HorizontalScrollBarVisibility == ScrollBarVisibility.Disabled && scroll.HorizontalOffset == 0 &&
            scroll.ExtentWidth <= scroll.ViewportWidth + 1, "production Playnite modal keeps finite horizontal measure despite its long description");
        var posterSlot = LayoutInformation.GetLayoutSlot(poster);
        var posterOrigin = Find<Grid>(prefix + "overview-header")!.TransformToVisual(scroll).TransformPoint(new(posterSlot.X, posterSlot.Y));
        Check(posterOrigin.X >= 0 && posterOrigin.X + posterSlot.Width <= scroll.ViewportWidth + 1 && poster.ActualHeight > 200,
            "production Playnite decoded poster remains inside the modal viewport after focus reveal");
        var tabs = snapshot.Root.Children[1];
        var tabButtons = Walk(tabs).Where(node => node.ActionId?.StartsWith("playnite-library.details.tab.", StringComparison.Ordinal) == true).ToArray();
        Check(tabButtons.Length == 3 && tabButtons.All(node =>
        {
            var button = Find<Button>("Widget." + node.Id)!;
            var origin = button.TransformToVisual(scroll).TransformPoint(new(0, 0));
            return button.ActualWidth > 20 && origin.X >= 0 && origin.X + button.ActualWidth <= scroll.ViewportWidth + 1;
        }), "all three production details navigation options fit the finite modal width");
        var originalExtent = scroll.ExtentHeight;
        presenter.Width = 600;
        await Wait(() => scroll.ViewportWidth < 570);
        Check(scroll.ExtentWidth <= scroll.ViewportWidth + 1 && scroll.ExtentHeight >= originalExtent,
            "production modal resize wraps description vertically without leaking horizontal extent");
        presenter.WriteLayoutDiagnostics(Path.Combine(Path.GetDirectoryName(path)!, "Native-Details-Geometry.winui-layout.json"));

        static IEnumerable<ViewNode> Walk(ViewNode root)
        {
            yield return root;
            foreach (var child in root.Children)
                foreach (var node in Walk(child)) yield return node;
        }
    }
}
