using System.Globalization;
using System.Reflection;
using System.Text;
using System.Text.Json;
using WidgetRail.WidgetProtocol;

const string artifactRelativePath = "src/OverlayHost/WidgetProtocolPresentationContract.generated.h";

var repositoryRoot = FindRepositoryRoot(AppContext.BaseDirectory);
var artifactPath = Path.Combine(repositoryRoot, artifactRelativePath.Replace('/', Path.DirectorySeparatorChar));
var expected = GenerateArtifact();

if (args is ["--write"])
{
    File.WriteAllText(artifactPath, expected, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    Console.WriteLine($"Wrote {artifactRelativePath} from {nameof(ProtocolConstants)}.");
    return 0;
}

if (args.Length != 0 && args is not ["--verify"])
{
    Console.Error.WriteLine("Usage: WidgetProtocol.ContractParity.Tests [--verify|--write]");
    return 2;
}

if (!File.Exists(artifactPath))
{
    Console.Error.WriteLine($"Presentation contract artifact is missing: {artifactRelativePath}");
    return 1;
}

var actual = File.ReadAllText(artifactPath);
if (!string.Equals(actual, expected, StringComparison.Ordinal))
{
    Console.Error.WriteLine(
        $"Presentation contract drift: regenerate {artifactRelativePath} from {nameof(ProtocolConstants)}.");
    return 1;
}

VerifyDriftDetection(expected);
Console.WriteLine(
    $"Widget protocol presentation contract parity passed: {ContractFields().Length} managed constants, {ControllerShortcutResolutionContract.RepeatMatchRules.Count} shortcut-repeat rules, and {ControllerShortcutResolutionContract.OwnerAvailabilityRules.Length} owner-availability rules match the native Release artifact exactly; missing, added, renamed, and changed-value drift fail closed.");
return 0;

static string FindRepositoryRoot(string start)
{
    for (var candidate = new DirectoryInfo(start); candidate is not null; candidate = candidate.Parent)
    {
        if (File.Exists(Path.Combine(candidate.FullName, "src", "WidgetProtocol", "ProtocolConstants.cs")))
            return candidate.FullName;
    }
    throw new InvalidOperationException("Could not locate the repository root.");
}

static FieldInfo[] ContractFields() => typeof(ProtocolConstants)
    .GetFields(BindingFlags.Public | BindingFlags.Static)
    .Concat(typeof(PinnedSurfaceContract).GetFields(
        BindingFlags.NonPublic | BindingFlags.Static))
    .Where(field => field.IsLiteral && !field.IsInitOnly)
    .OrderBy(field => field.Name, StringComparer.Ordinal)
    .ToArray();

static string GenerateArtifact()
{
    var output = new StringBuilder();
    output.AppendLine("// <auto-generated>");
    output.AppendLine("// Generated from WidgetProtocol.ProtocolConstants by WidgetProtocol.ContractParity.Tests.");
    output.AppendLine("// Do not edit values here; run the named parity generator instead.");
    output.AppendLine("// </auto-generated>");
    output.AppendLine("#pragma once");
    output.AppendLine();
    output.AppendLine("#include <array>");
    output.AppendLine("#include <cstdint>");
    output.AppendLine("#include <string_view>");
    output.AppendLine();
    output.AppendLine("namespace widgetrail::protocol_contract {");
    output.AppendLine();

    foreach (var field in ContractFields())
    {
        var value = field.GetRawConstantValue() ??
            throw new InvalidOperationException($"{field.Name} has no literal value.");
        var (type, literal) = value switch
        {
            int number => ("std::int32_t", number.ToString(CultureInfo.InvariantCulture)),
            long number => ("std::int64_t", number.ToString(CultureInfo.InvariantCulture) + "LL"),
            double number => ("double", RenderDouble(number)),
            string text => ("std::wstring_view", RenderWideString(text)),
            _ => throw new InvalidOperationException(
                $"Unsupported presentation contract type {field.FieldType.Name} for {field.Name}."),
        };
        output.Append("inline constexpr ").Append(type).Append(' ').Append(field.Name)
            .Append(" = ").Append(literal).AppendLine(";");
    }

    output.AppendLine();
    output.AppendLine("struct ControllerShortcutRepeatMatchRule final {");
    output.AppendLine("    std::wstring_view inputPhase;");
    output.AppendLine("    std::wstring_view shortcutPhase;");
    output.AppendLine("    std::wstring_view repeatPolicy;");
    output.AppendLine("};");
    output.AppendLine();
    output.Append("inline constexpr std::array<ControllerShortcutRepeatMatchRule, ")
        .Append(ControllerShortcutResolutionContract.RepeatMatchRules.Count)
        .AppendLine("> ControllerShortcutRepeatMatchRules{{");
    foreach (var rule in ControllerShortcutResolutionContract.RepeatMatchRules)
    {
        output.Append("    {")
            .Append(RenderWideString(WireToken(rule.InputPhase))).Append(", ")
            .Append(RenderWideString(WireToken(rule.ShortcutPhase))).Append(", ")
            .Append(RenderWideString(WireToken(rule.RepeatPolicy))).AppendLine("},");
    }
    output.AppendLine("}};");
    output.AppendLine();
    output.AppendLine("[[nodiscard]] inline constexpr bool ControllerShortcutMatches(");
    output.AppendLine("    const std::wstring_view shortcutButton,");
    output.AppendLine("    const std::wstring_view shortcutPhase,");
    output.AppendLine("    const std::wstring_view repeatPolicy,");
    output.AppendLine("    const std::wstring_view inputButton,");
    output.AppendLine("    const std::wstring_view inputPhase) noexcept {");
    output.AppendLine("    if (shortcutButton != inputButton) return false;");
    output.AppendLine("    if (shortcutPhase == inputPhase) return true;");
    output.AppendLine("    for (const auto& rule : ControllerShortcutRepeatMatchRules) {");
    output.AppendLine("        if (rule.inputPhase == inputPhase &&");
    output.AppendLine("            rule.shortcutPhase == shortcutPhase &&");
    output.AppendLine("            rule.repeatPolicy == repeatPolicy) return true;");
    output.AppendLine("    }");
    output.AppendLine("    return false;");
    output.AppendLine("}");
    output.AppendLine();
    output.AppendLine("struct ControllerShortcutOwnerAvailabilityRule final {");
    output.AppendLine("    bool disabled;");
    output.AppendLine("    bool busy;");
    output.AppendLine("    bool available;");
    output.AppendLine("};");
    output.AppendLine();
    output.Append("inline constexpr std::array<ControllerShortcutOwnerAvailabilityRule, ")
        .Append(ControllerShortcutResolutionContract.OwnerAvailabilityRules.Length)
        .AppendLine("> ControllerShortcutOwnerAvailabilityRules{{");
    foreach (var rule in ControllerShortcutResolutionContract.OwnerAvailabilityRules)
    {
        output.Append("    {")
            .Append(RenderBool(rule.IsDisabled)).Append(", ")
            .Append(RenderBool(rule.IsBusy)).Append(", ")
            .Append(RenderBool(rule.IsAvailable)).AppendLine("},");
    }
    output.AppendLine("}};");
    output.AppendLine();
    output.AppendLine("[[nodiscard]] inline constexpr bool ControllerShortcutOwnerAvailable(");
    output.AppendLine("    const bool disabled, const bool busy) noexcept {");
    output.AppendLine("    for (const auto& rule : ControllerShortcutOwnerAvailabilityRules) {");
    output.AppendLine("        if (rule.disabled == disabled && rule.busy == busy)");
    output.AppendLine("            return rule.available;");
    output.AppendLine("    }");
    output.AppendLine("    return false;");
    output.AppendLine("}");

    output.AppendLine();
    output.AppendLine("} // namespace widgetrail::protocol_contract");
    return output.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
}

static string WireToken<T>(T value) where T : struct, Enum =>
    JsonNamingPolicy.CamelCase.ConvertName(value.ToString());

static string RenderWideString(string value)
{
    if (value.Any(character => character is '"' or '\\' or '\r' or '\n'))
        throw new InvalidOperationException("Shortcut contract wire tokens must be simple literals.");
    return $"L\"{value}\"";
}

static string RenderBool(bool value) => value ? "true" : "false";

static string RenderDouble(double value)
{
    if (!double.IsFinite(value))
        throw new InvalidOperationException("Presentation contract doubles must be finite.");
    var literal = value.ToString("R", CultureInfo.InvariantCulture);
    return literal.Contains('.', StringComparison.Ordinal) ||
           literal.Contains('E', StringComparison.OrdinalIgnoreCase)
        ? literal
        : literal + ".0";
}

static void VerifyDriftDetection(string artifact)
{
    var firstField = ContractFields()[0];
    var firstLine = artifact.Split('\n', StringSplitOptions.RemoveEmptyEntries)
        .Single(line => line.Contains($" {firstField.Name} = ", StringComparison.Ordinal)) + "\n";
    var availabilityLine = artifact.Split('\n', StringSplitOptions.RemoveEmptyEntries)
        .Single(line => line.Contains("{false, false, true}", StringComparison.Ordinal)) + "\n";
    var fullWidgetLayoutLine = artifact.Split('\n', StringSplitOptions.RemoveEmptyEntries)
        .Single(line => line.Contains(
            $" {nameof(PinnedSurfaceContract.FullWidgetLayoutId)} = ",
            StringComparison.Ordinal)) + "\n";

    var vectors = new[]
    {
        artifact.Replace(firstLine, string.Empty, StringComparison.Ordinal),
        artifact + "inline constexpr std::int32_t UnexpectedPresentationLimit = 1;\n",
        artifact.Replace($" {firstField.Name} =", $" Renamed{firstField.Name} =",
            StringComparison.Ordinal),
        artifact.Replace(firstLine, firstLine.Replace(" = ", " = -1 + ",
            StringComparison.Ordinal), StringComparison.Ordinal),
        artifact.Replace(
            availabilityLine,
            availabilityLine.Replace("true", "false", StringComparison.Ordinal),
            StringComparison.Ordinal),
        artifact.Replace(
            fullWidgetLayoutLine,
            fullWidgetLayoutLine.Replace(
                "host.full-widget", "host.changed", StringComparison.Ordinal),
            StringComparison.Ordinal),
    };
    if (vectors.Any(candidate => string.Equals(candidate, artifact, StringComparison.Ordinal)))
        throw new InvalidOperationException("A deterministic presentation-contract drift vector was not rejected.");
}
