<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\samples\YtMusicWidget\YtMusicWidget.csproj" />
    <ProjectReference Include="..\..\src\WidgetProtocol\WidgetProtocol.csproj" />
    <ProjectReference Include="..\..\src\WidgetStyling\WidgetStyling.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\samples\YtMusicWidget\YtMusicWidget.cs" Link="source\YtMusicWidget.cs" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\samples\YtMusicWidget\YtMusicActionPolicy.cs" Link="source\YtMusicActionPolicy.cs" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\samples\YtMusicWidget\YtMusicCompanionPolicy.cs" Link="source\YtMusicCompanionPolicy.cs" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\samples\YtMusicWidget\YtMusicConnectionPolicy.cs" Link="source\YtMusicConnectionPolicy.cs" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\samples\YtMusicWidget\YtMusicPresentation.cs" Link="source\YtMusicPresentation.cs" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
