using System.Text.Json.Serialization;
using WidgetRail.WidgetSdk;

namespace WidgetRail.WidgetBridge;

// Closed presentation transport roots; nested contracts are generated recursively.
[JsonSerializable(typeof(BridgeEnvelope))]
[JsonSerializable(typeof(BridgeHello))]
[JsonSerializable(typeof(WidgetIdRequest))]
[JsonSerializable(typeof(BridgeEmptyPayload))]
[JsonSerializable(typeof(BridgeDisplayIdentity))]
[JsonSerializable(typeof(BridgeAppearanceRequest))]
[JsonSerializable(typeof(BridgePresentationRequest))]
[JsonSerializable(typeof(BridgeArtworkRequest))]
[JsonSerializable(typeof(BridgePackageIconRequest))]
[JsonSerializable(typeof(BridgeEmbeddedMediaRequest))]
[JsonSerializable(typeof(BridgeEmbeddedMediaResource))]
[JsonSerializable(typeof(BridgeEmbeddedMediaBundle))]
[JsonSerializable(typeof(BridgeEmbeddedMediaPlaybackEventRequest))]
[JsonSerializable(typeof(BridgeWidgetLifecycleRequest))]
[JsonSerializable(typeof(BridgePresentationEstablishment))]
[JsonSerializable(typeof(BridgePinnedActionRequest))]
[JsonSerializable(typeof(BridgePinnedArtworkRequest))]
[JsonSerializable(typeof(BridgeActionRequest))]
[JsonSerializable(typeof(BridgeQuickActionRequest))]
[JsonSerializable(typeof(BridgeControllerInputRequest))]
[JsonSerializable(typeof(BridgeProtectedWifiRequest))]
[JsonSerializable(typeof(BridgeLocalWidgetPackageOrigin))]
[JsonSerializable(typeof(BridgeLocalWidgetPackageInstallRequest))]
[JsonSerializable(typeof(BridgeLocalWidgetPackageInstallCancelRequest))]
[JsonSerializable(typeof(BridgeLocalWidgetPackageInstallApprovalRequest))]
[JsonSerializable(typeof(BridgeLocalWidgetPackageInstallCompleted))]
[JsonSerializable(typeof(BridgeInvalidation))]
[JsonSerializable(typeof(BridgeAppearanceChanged))]
[JsonSerializable(typeof(BridgeCatalogChangedEvent))]
[JsonSerializable(typeof(BridgeError))]
[JsonSerializable(typeof(BridgeEncodedArtworkEvent))]
[JsonSerializable(typeof(BridgeLegacyArtworkEvent))]
[JsonSerializable(typeof(BridgeIndexedRangeRequest))]
[JsonSerializable(typeof(BridgeIndexedRangeResponse))]
[JsonSerializable(typeof(BridgeIndexedLeaseResponse))]
[JsonSerializable(typeof(BridgeResolvedStyleSnapshot))]
[JsonSerializable(typeof(BridgePresentationStylesRequest))]
[JsonSerializable(typeof(BridgePresentationStylesResponse))]
[JsonSerializable(typeof(BridgeIndexedStylesResponse))]
[JsonSerializable(typeof(BridgeIndexedLeaseRequest))]
[JsonSerializable(typeof(BridgeIndexedInputRequest))]
[JsonSerializable(typeof(BridgeIndexedArtworkRequest))]
[JsonSerializable(typeof(BridgeIndexedArtworkResponse))]
[JsonSerializable(typeof(BridgeWidgetDescriptor[]))]
[JsonSerializable(typeof(Dictionary<string, BridgeNodeRenderStyles>))]
[JsonSerializable(typeof(Dictionary<string, BridgeComputedStyleValue>))]
[JsonSerializable(typeof(WidgetLifecycleState))]
[JsonSerializable(typeof(WidgetOperationAdmission))]
[JsonSerializable(typeof(PinnedActionResult))]
internal sealed partial class BridgeJsonContext : JsonSerializerContext;
