<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PlatformDiagnostics\PlatformDiagnostics.csproj" />
    <ProjectReference Include="..\PlatformSettings\PlatformSettings.csproj" />
    <ProjectReference Include="..\WidgetProtocol\WidgetProtocol.csproj" />
    <ProjectReference Include="..\WidgetSdk\WidgetSdk.csproj" />
    <ProjectReference Include="..\WidgetStyling\WidgetStyling.csproj" />
  </ItemGroup>
</Project>
