<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\samples\YtMusicWidget\YtMusicWidget.csproj" />
    <ProjectReference Include="..\..\src\WidgetStyling\WidgetStyling.csproj" />
    <None Include="..\..\samples\YtMusicWidget\styles\default.wrss" Link="standalone.wrss" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
