<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="RuntimeProtocol.cs" />
    <Compile Remove="WidgetWorkerNotificationLane.cs" />
    <Compile Remove="WidgetWorkerServer.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PlatformBroker\PlatformBroker.csproj" />
    <ProjectReference Include="..\WidgetApplicationRuntime\WidgetApplicationRuntime.csproj" />
    <ProjectReference Include="..\WidgetSdk\WidgetSdk.csproj" />
  </ItemGroup>
</Project>
