// <auto-generated>
// Generated from WidgetProtocol.ProtocolConstants by WidgetProtocol.ContractParity.Tests.
// Do not edit values here; run the named parity generator instead.
// </auto-generated>
#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace widgetrail::protocol_contract {

inline constexpr std::int32_t ActionSurfaceVersion = 7;
inline constexpr std::int32_t AnchoredSelectVersion = 41;
inline constexpr std::int32_t AtomicPresentationUpdateVersion = 18;
inline constexpr std::int32_t BackgroundSurfaceVersion = 38;
inline constexpr std::int32_t BaselineVersion = 1;
inline constexpr std::int32_t CollectionGenerationVersion = 49;
inline constexpr std::int32_t CollectionLoadingVersion = 48;
inline constexpr std::int32_t CollectionPositionVersion = 47;
inline constexpr std::int32_t CollectionResetGenerationVersion = 50;
inline constexpr std::int32_t CompactPinnedMediaPresentationVersion = 25;
inline constexpr std::int32_t ContextActionsVersion = 34;
inline constexpr std::int32_t ContextMenuTriggerVersion = 51;
inline constexpr std::int32_t ControllerShortcutLabelVersion = 43;
inline constexpr std::int32_t CurrentHostApiMajor = 1;
inline constexpr std::int32_t CurrentManifestVersion = 1;
inline constexpr std::int32_t CurrentVersion = 52;
inline constexpr std::int32_t CursorCollectionVersion = 14;
inline constexpr std::int32_t DashboardGestureAuthorityVersion = 4;
inline constexpr double DefaultMediaSeekStepSeconds = 10.0;
inline constexpr std::int32_t DeferredFocusGroupEntryVersion = 45;
inline constexpr std::int32_t EmbeddedMediaFrameDomainFamiliesVersion = 26;
inline constexpr std::int32_t EmbeddedMediaPlaybackPreferencesVersion = 27;
inline constexpr std::int32_t EmbeddedMediaPlaybackVersion = 24;
inline constexpr std::int32_t EmbeddedMediaSessionVersion = 42;
inline constexpr std::int32_t EmbeddedMediaSurfaceVersion = 22;
inline constexpr std::int32_t FocusAssociatedPresentationVersion = 40;
inline constexpr std::int32_t FocusGroupEntryRequestVersion = 44;
inline constexpr std::int32_t FocusPersistenceVersion = 13;
inline constexpr std::int32_t FocusedBackgroundArtworkVersion = 39;
inline constexpr std::wstring_view FullWidgetLayoutId = L"host.full-widget";
inline constexpr std::int32_t FullscreenGlyphVersion = 46;
inline constexpr std::int32_t HeldButtonActionRepeatVersion = 32;
inline constexpr std::int32_t InlinePngImageVersion = 6;
inline constexpr std::int32_t LoadingIndicatorVersion = 5;
inline constexpr std::int32_t MaximumActionSurfaceDescendants = 32;
inline constexpr std::int32_t MaximumActionSurfaceDirectChildren = 8;
inline constexpr std::int32_t MaximumActionSurfaceRelativeDepth = 4;
inline constexpr std::int32_t MaximumCapabilityIdLength = 128;
inline constexpr std::int32_t MaximumContextActionCount = 8;
inline constexpr std::int32_t MaximumCursorCollectionItems = 256;
inline constexpr std::int32_t MaximumDecodedArtworkBytes = 67108864;
inline constexpr std::int32_t MaximumEmbeddedMediaAggregateBytes = 524288;
inline constexpr std::int32_t MaximumEmbeddedMediaCommandCount = 8;
inline constexpr std::int32_t MaximumEmbeddedMediaContentTypeLength = 96;
inline constexpr std::int32_t MaximumEmbeddedMediaFrameDomainFamilyAggregateLength = 512;
inline constexpr std::int32_t MaximumEmbeddedMediaFrameDomainFamilyCount = 4;
inline constexpr std::int32_t MaximumEmbeddedMediaFrameDomainFamilyLength = 253;
inline constexpr std::int32_t MaximumEmbeddedMediaFrameOriginCount = 8;
inline constexpr std::int32_t MaximumEmbeddedMediaFrameOriginLength = 256;
inline constexpr std::int32_t MaximumEmbeddedMediaKeyLength = 128;
inline constexpr double MaximumEmbeddedMediaPlaybackRate = 2.0;
inline constexpr std::int32_t MaximumEmbeddedMediaResourceBytes = 262144;
inline constexpr std::int32_t MaximumEmbeddedMediaResourceCount = 16;
inline constexpr std::int32_t MaximumEmbeddedMediaResourcePathLength = 160;
inline constexpr std::int32_t MaximumEncodedArtworkBytes = 8388608;
inline constexpr std::int32_t MaximumEncodedArtworkDimension = 4096;
inline constexpr std::int32_t MaximumEncodedArtworkFrameBytes = 12582912;
inline constexpr std::int32_t MaximumEncodedArtworkPixels = 16777216;
inline constexpr std::int64_t MaximumFocusGroupEntryRequestId = 9007199254740991LL;
inline constexpr std::int32_t MaximumFocusPresentationDepth = 8;
inline constexpr std::int32_t MaximumFocusPresentationNodes = 64;
inline constexpr double MaximumGridColumnWidth = 1600.0;
inline constexpr std::int32_t MaximumGridColumns = 32;
inline constexpr std::int32_t MaximumInlinePngBytes = 12288;
inline constexpr std::int32_t MaximumInlinePngDimension = 64;
inline constexpr std::int32_t MaximumInlinePngSourceLength = 16406;
inline constexpr std::int32_t MaximumManifestPermissionCount = 32;
inline constexpr double MaximumMediaSeekStepSeconds = 60.0;
inline constexpr std::int32_t MaximumNodeCount = 2048;
inline constexpr std::int32_t MaximumPackageIconAggregateBytes = 524288;
inline constexpr std::int32_t MaximumPackageIconAssetCount = 32;
inline constexpr std::int32_t MaximumPackageIconAssetIdLength = 64;
inline constexpr std::int32_t MaximumPackageIconBytes = 65536;
inline constexpr std::int32_t MaximumPackageIconPathLength = 160;
inline constexpr std::int32_t MaximumPackageIconRasterDimension = 512;
inline constexpr std::int32_t MaximumPendingPresentationUpdateBytes = 524288;
inline constexpr std::int32_t MaximumPendingPresentationUpdates = 4;
inline constexpr std::int32_t MaximumPinnedPresentationAggregateNodeCount = 2048;
inline constexpr std::int32_t MaximumPinnedPresentationAggregateResourceCount = 256;
inline constexpr std::int32_t MaximumPinnedPresentationAggregateStringLength = 262144;
inline constexpr std::int32_t MaximumPinnedPresentationLayoutCount = 8;
inline constexpr std::int32_t MaximumPinnedPresentationLayoutNameLength = 96;
inline constexpr std::int32_t MaximumPresentationUpdateBytes = 262144;
inline constexpr std::int32_t MaximumPresentationUpdateOperations = 256;
inline constexpr std::int32_t MaximumQuickActionCount = 3;
inline constexpr std::int32_t MaximumScrollPaginationThreshold = 8;
inline constexpr std::int32_t MaximumSelectOptionCount = 128;
inline constexpr std::int32_t MaximumStringLength = 4096;
inline constexpr std::int32_t MaximumStyleClassCount = 32;
inline constexpr std::int32_t MaximumStyleClassLength = 64;
inline constexpr double MaximumSurfaceHeight = 1200.0;
inline constexpr double MaximumSurfaceWidth = 1600.0;
inline constexpr std::int32_t MaximumTextEntryLength = 96;
inline constexpr std::int32_t MaximumTreeDepth = 32;
inline constexpr double MaximumVirtualCollectionExtent = 1000000.0;
inline constexpr double MaximumVirtualCollectionItemExtent = 512.0;
inline constexpr std::int32_t MaximumVirtualCollectionItems = 1000000;
inline constexpr std::int64_t MaximumVirtualCollectionRequestGeneration = 9007199254740991LL;
inline constexpr std::int32_t MediaViewportVersion = 23;
inline constexpr double MinimumEmbeddedMediaPlaybackRate = 0.5;
inline constexpr double MinimumGridColumnWidth = 44.0;
inline constexpr double MinimumMediaSeekStepSeconds = 1.0;
inline constexpr std::int32_t MinimumSupportedVersion = 1;
inline constexpr double MinimumSurfaceHeight = 180.0;
inline constexpr double MinimumSurfaceWidth = 240.0;
inline constexpr double MinimumVirtualCollectionItemExtent = 1.0;
inline constexpr std::int32_t OverlayFullscreenMediaPresentationVersion = 30;
inline constexpr std::int32_t PackageSvgIconVersion = 46;
inline constexpr std::int32_t PinnedPresentationLayoutsVersion = 20;
inline constexpr std::int32_t PinnedPresentationProjectionsVersion = 21;
inline constexpr std::int32_t PosterTileVersion = 37;
inline constexpr std::int32_t RememberedChildFocusGroupVersion = 33;
inline constexpr std::int32_t RepeatOneGlyphVersion = 12;
inline constexpr std::int32_t ResponsiveGridVersion = 8;
inline constexpr std::int32_t ResponsiveVisibilityVersion = 9;
inline constexpr std::int32_t RetainedHiddenEmbeddedMediaVersion = 29;
inline constexpr std::int32_t ScrollContainerVersion = 2;
inline constexpr std::int32_t ScrollPaginationVersion = 11;
inline constexpr std::int32_t SemanticSeekGlyphVersion = 31;
inline constexpr std::int32_t SensitiveTextEntryVersion = 28;
inline constexpr std::int32_t SliderActivationVersion = 10;
inline constexpr std::int32_t SliderVersion = 3;
inline constexpr std::int32_t SurfaceAppearanceVersion = 35;
inline constexpr std::int32_t SurfaceAxisSizingVersion = 17;
inline constexpr std::int32_t SurfaceHintsVersion = 2;
inline constexpr std::int32_t TextEntryVersion = 15;
inline constexpr std::int32_t TrustedEncodedArtworkVersion = 36;
inline constexpr std::int32_t VirtualCollectionWindowVersion = 19;
inline constexpr std::int32_t WindowPreviewVersion = 52;

struct ControllerShortcutRepeatMatchRule final {
    std::wstring_view inputPhase;
    std::wstring_view shortcutPhase;
    std::wstring_view repeatPolicy;
};

inline constexpr std::array<ControllerShortcutRepeatMatchRule, 1> ControllerShortcutRepeatMatchRules{{
    {L"repeated", L"pressed", L"whileHeld"},
}};

[[nodiscard]] inline constexpr bool ControllerShortcutMatches(
    const std::wstring_view shortcutButton,
    const std::wstring_view shortcutPhase,
    const std::wstring_view repeatPolicy,
    const std::wstring_view inputButton,
    const std::wstring_view inputPhase) noexcept {
    if (shortcutButton != inputButton) return false;
    if (shortcutPhase == inputPhase) return true;
    for (const auto& rule : ControllerShortcutRepeatMatchRules) {
        if (rule.inputPhase == inputPhase &&
            rule.shortcutPhase == shortcutPhase &&
            rule.repeatPolicy == repeatPolicy) return true;
    }
    return false;
}

struct ControllerShortcutOwnerAvailabilityRule final {
    bool disabled;
    bool busy;
    bool available;
};

inline constexpr std::array<ControllerShortcutOwnerAvailabilityRule, 4> ControllerShortcutOwnerAvailabilityRules{{
    {false, false, true},
    {false, true, false},
    {true, false, false},
    {true, true, false},
}};

[[nodiscard]] inline constexpr bool ControllerShortcutOwnerAvailable(
    const bool disabled, const bool busy) noexcept {
    for (const auto& rule : ControllerShortcutOwnerAvailabilityRules) {
        if (rule.disabled == disabled && rule.busy == busy)
            return rule.available;
    }
    return false;
}

} // namespace widgetrail::protocol_contract
