// <auto-generated>
// Generated from WidgetProtocol.ProtocolConstants by WidgetProtocol.ContractParity.Tests.
// Do not edit values here; run the named parity generator instead.
// </auto-generated>
#pragma once

#include <cstdint>

namespace widgetrail::protocol_contract {

inline constexpr std::int32_t ActionSurfaceVersion = 7;
inline constexpr std::int32_t AtomicPresentationUpdateVersion = 18;
inline constexpr std::int32_t BaselineVersion = 1;
inline constexpr std::int32_t CurrentHostApiMajor = 1;
inline constexpr std::int32_t CurrentManifestVersion = 1;
inline constexpr std::int32_t CurrentVersion = 25;
inline constexpr std::int32_t CursorCollectionVersion = 14;
inline constexpr std::int32_t DashboardGestureAuthorityVersion = 4;
inline constexpr std::int32_t EmbeddedMediaPlaybackVersion = 24;
inline constexpr std::int32_t CompactPinnedMediaPresentationVersion = 25;
inline constexpr double DefaultCompactPinnedMediaSeekStepSeconds = 10.0;
inline constexpr std::int32_t EmbeddedMediaSurfaceVersion = 22;
inline constexpr std::int32_t FocusPersistenceVersion = 13;
inline constexpr std::int32_t InlinePngImageVersion = 6;
inline constexpr std::int32_t LoadingIndicatorVersion = 5;
inline constexpr std::int32_t MaximumActionSurfaceDescendants = 32;
inline constexpr std::int32_t MaximumActionSurfaceDirectChildren = 8;
inline constexpr std::int32_t MaximumActionSurfaceRelativeDepth = 4;
inline constexpr std::int32_t MaximumCapabilityIdLength = 128;
inline constexpr std::int32_t MaximumCursorCollectionItems = 256;
inline constexpr std::int32_t MaximumEmbeddedMediaAggregateBytes = 524288;
inline constexpr std::int32_t MaximumEmbeddedMediaCommandCount = 8;
inline constexpr std::int32_t MaximumEmbeddedMediaContentTypeLength = 96;
inline constexpr std::int32_t MaximumEmbeddedMediaFrameOriginCount = 8;
inline constexpr std::int32_t MaximumEmbeddedMediaFrameOriginLength = 256;
inline constexpr std::int32_t MaximumEmbeddedMediaKeyLength = 128;
inline constexpr std::int32_t MaximumEmbeddedMediaResourceBytes = 262144;
inline constexpr std::int32_t MaximumEmbeddedMediaResourceCount = 16;
inline constexpr std::int32_t MaximumEmbeddedMediaResourcePathLength = 160;
inline constexpr double MaximumCompactPinnedMediaSeekStepSeconds = 60.0;
inline constexpr double MaximumGridColumnWidth = 1600.0;
inline constexpr std::int32_t MaximumGridColumns = 32;
inline constexpr std::int32_t MaximumInlinePngBytes = 12288;
inline constexpr std::int32_t MaximumInlinePngDimension = 64;
inline constexpr std::int32_t MaximumInlinePngSourceLength = 16406;
inline constexpr std::int32_t MaximumManifestPermissionCount = 32;
inline constexpr std::int32_t MaximumNodeCount = 2048;
inline constexpr std::int32_t MaximumPendingPresentationUpdateBytes = 524288;
inline constexpr std::int32_t MaximumPendingPresentationUpdates = 4;
inline constexpr std::int32_t MaximumPinnedPresentationAggregateNodeCount = 2048;
inline constexpr std::int32_t MaximumPinnedPresentationAggregateResourceCount = 256;
inline constexpr std::int32_t MaximumPinnedPresentationAggregateStringLength = 262144;
inline constexpr std::int32_t MaximumPinnedPresentationLayoutCount = 8;
inline constexpr std::int32_t MaximumPinnedPresentationLayoutNameLength = 96;
inline constexpr std::int32_t MaximumPresentationUpdateBytes = 262144;
inline constexpr std::int32_t MaximumPresentationUpdateOperations = 256;
inline constexpr std::int32_t MaximumQuickActionCount = 3;
inline constexpr std::int32_t MaximumScrollPaginationThreshold = 8;
inline constexpr std::int32_t MaximumStringLength = 4096;
inline constexpr std::int32_t MaximumStyleClassCount = 32;
inline constexpr std::int32_t MaximumStyleClassLength = 64;
inline constexpr double MaximumSurfaceHeight = 1200.0;
inline constexpr double MaximumSurfaceWidth = 1600.0;
inline constexpr std::int32_t MaximumTextEntryLength = 96;
inline constexpr std::int32_t MaximumTreeDepth = 32;
inline constexpr double MaximumVirtualCollectionExtent = 1000000.0;
inline constexpr double MaximumVirtualCollectionItemExtent = 512.0;
inline constexpr std::int32_t MaximumVirtualCollectionItems = 1000000;
inline constexpr std::int64_t MaximumVirtualCollectionRequestGeneration = 9007199254740991LL;
inline constexpr std::int32_t MediaViewportVersion = 23;
inline constexpr double MinimumCompactPinnedMediaSeekStepSeconds = 1.0;
inline constexpr double MinimumGridColumnWidth = 44.0;
inline constexpr std::int32_t MinimumSupportedVersion = 1;
inline constexpr double MinimumSurfaceHeight = 180.0;
inline constexpr double MinimumSurfaceWidth = 240.0;
inline constexpr double MinimumVirtualCollectionItemExtent = 1.0;
inline constexpr std::int32_t PinnedPresentationLayoutsVersion = 20;
inline constexpr std::int32_t PinnedPresentationProjectionsVersion = 21;
inline constexpr std::int32_t RepeatOneGlyphVersion = 12;
inline constexpr std::int32_t ResponsiveGridVersion = 8;
inline constexpr std::int32_t ResponsiveVisibilityVersion = 9;
inline constexpr std::int32_t ScrollContainerVersion = 2;
inline constexpr std::int32_t ScrollPaginationVersion = 11;
inline constexpr std::int32_t SliderActivationVersion = 10;
inline constexpr std::int32_t SliderVersion = 3;
inline constexpr std::int32_t SurfaceAxisSizingVersion = 17;
inline constexpr std::int32_t SurfaceHintsVersion = 2;
inline constexpr std::int32_t TextEntryVersion = 15;
inline constexpr std::int32_t VirtualCollectionWindowVersion = 19;

} // namespace widgetrail::protocol_contract
