using System.Globalization;
using System.Reflection;
using System.Text;

internal static class WidgetSdkPublicApi
{
    private const string Header = "# WidgetSdk public API baseline v1";
    private static readonly NullabilityInfoContext Nullability = new();

    public static IReadOnlyList<string> Generate(Assembly assembly)
    {
        var symbols = new List<string>();
        foreach (var type in assembly.GetExportedTypes().OrderBy(TypeIdentity, StringComparer.Ordinal))
        {
            symbols.Add(TypeDeclaration(type));
            if (type.IsEnum)
            {
                foreach (var field in type.GetFields(BindingFlags.Public | BindingFlags.Static)
                             .OrderBy(field => field.Name, StringComparer.Ordinal))
                    symbols.Add($"enum {TypeIdentity(type)}.{field.Name} = {Constant(field.GetRawConstantValue(), field.FieldType)}");
                continue;
            }

            foreach (var constructor in type.GetConstructors(
                         BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
                         .OrderBy(ConstructorIdentity, StringComparer.Ordinal))
                symbols.Add(ConstructorIdentity(constructor));
            foreach (var field in type.GetFields(
                         BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
                         .OrderBy(FieldIdentity, StringComparer.Ordinal))
                symbols.Add(FieldIdentity(field));
            foreach (var property in type.GetProperties(
                         BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
                         .Where(property => property.GetMethod?.IsPublic == true || property.SetMethod?.IsPublic == true)
                         .OrderBy(PropertyIdentity, StringComparer.Ordinal))
                symbols.Add(PropertyIdentity(property));
            foreach (var eventInfo in type.GetEvents(
                         BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
                         .OrderBy(EventIdentity, StringComparer.Ordinal))
                symbols.Add(EventIdentity(eventInfo));
            foreach (var method in type.GetMethods(
                         BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
                         .Where(method => !method.IsSpecialName || method.Name.StartsWith("op_", StringComparison.Ordinal))
                         .OrderBy(MethodIdentity, StringComparer.Ordinal))
                symbols.Add(MethodIdentity(method));
        }
        var duplicate = symbols.GroupBy(symbol => symbol, StringComparer.Ordinal)
            .FirstOrDefault(group => group.Count() > 1);
        if (duplicate is not null)
            throw new InvalidOperationException(
                $"Public API renderer produced duplicate identity '{duplicate.Key}'. Refine the canonical signature before updating the baseline.");
        return symbols.Order(StringComparer.Ordinal).ToArray();
    }

    public static string Serialize(IReadOnlyList<string> symbols)
    {
        var output = new StringBuilder();
        output.AppendLine(Header);
        output.AppendLine("# Generated by tests/WidgetSdk.Compatibility.Tests; review then use --update intentionally.");
        foreach (var symbol in symbols) output.AppendLine(symbol);
        return output.ToString();
    }

    public static IReadOnlyList<string> Parse(string text)
    {
        var lines = text.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Split('\n')
            .Select(line => line.Trim())
            .Where(line => line.Length != 0 && !line.StartsWith('#'))
            .ToArray();
        if (!text.StartsWith(Header + "\n", StringComparison.Ordinal) &&
            !text.StartsWith(Header + "\r\n", StringComparison.Ordinal))
            throw new InvalidOperationException("WidgetSdk public API baseline has an unsupported header.");
        if (lines.Length != lines.Distinct(StringComparer.Ordinal).Count())
            throw new InvalidOperationException("WidgetSdk public API baseline contains duplicate symbols.");
        if (!lines.SequenceEqual(lines.Order(StringComparer.Ordinal), StringComparer.Ordinal))
            throw new InvalidOperationException("WidgetSdk public API baseline is not ordinally sorted.");
        return lines;
    }

    private static string TypeDeclaration(Type type)
    {
        var modifiers = type.IsAbstract && type.IsSealed
            ? "static "
            : (type.IsAbstract ? "abstract " : type.IsSealed && !type.IsValueType ? "sealed " : string.Empty);
        var kind = type.IsEnum ? "enum" : type.IsInterface ? "interface" :
            typeof(MulticastDelegate).IsAssignableFrom(type.BaseType) ? "delegate" :
            type.IsValueType ? "struct" : "class";
        var bases = new List<string>();
        if (type.BaseType is not null && type.BaseType != typeof(object) &&
            type.BaseType != typeof(ValueType) && type.BaseType != typeof(Enum) &&
            type.BaseType != typeof(MulticastDelegate))
            bases.Add(FormatType(type.BaseType, null));
        bases.AddRange(type.GetInterfaces().Select(value => FormatType(value, null)));
        var declaration = $"type {modifiers}{kind} {TypeIdentity(type)}";
        if (bases.Count != 0)
            declaration += " : " + string.Join(", ", bases.Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal));
        return declaration + Constraints(type.GetGenericArguments());
    }

    private static string ConstructorIdentity(ConstructorInfo constructor) =>
        $"ctor {TypeIdentity(constructor.DeclaringType!)}({Parameters(constructor.GetParameters())})";

    private static string FieldIdentity(FieldInfo field)
    {
        var modifier = field.IsLiteral ? "const " : field.IsStatic ? "static " : string.Empty;
        if (field.IsInitOnly) modifier += "readonly ";
        var result = $"field {modifier}{FormatType(field.FieldType, Nullability.Create(field))} {TypeIdentity(field.DeclaringType!)}.{field.Name}";
        return field.IsLiteral ? result + " = " + Constant(field.GetRawConstantValue(), field.FieldType) : result;
    }

    private static string PropertyIdentity(PropertyInfo property)
    {
        var accessor = property.GetMethod ?? property.SetMethod!;
        var modifier = accessor.IsStatic ? "static " : string.Empty;
        var index = property.GetIndexParameters();
        var name = index.Length == 0
            ? property.Name
            : $"this[{Parameters(index)}]";
        var access = $"{{ {(property.GetMethod?.IsPublic == true ? "get; " : string.Empty)}{(property.SetMethod?.IsPublic == true ? "set; " : string.Empty)}}}";
        return $"property {modifier}{FormatType(property.PropertyType, Nullability.Create(property))} {TypeIdentity(property.DeclaringType!)}.{name} {access}";
    }

    private static string EventIdentity(EventInfo eventInfo)
    {
        var modifier = eventInfo.AddMethod?.IsStatic == true ? "static " : string.Empty;
        return $"event {modifier}{FormatType(eventInfo.EventHandlerType!, Nullability.Create(eventInfo))} {TypeIdentity(eventInfo.DeclaringType!)}.{eventInfo.Name}";
    }

    private static string MethodIdentity(MethodInfo method)
    {
        var modifiers = method.IsStatic ? "static " : string.Empty;
        if (method.IsAbstract) modifiers += "abstract ";
        else if (method.IsVirtual && method.GetBaseDefinition() == method) modifiers += "virtual ";
        var generic = method.IsGenericMethodDefinition
            ? "<" + string.Join(",", method.GetGenericArguments().Select(argument => argument.Name)) + ">"
            : string.Empty;
        return $"method {modifiers}{TypeIdentity(method.DeclaringType!)}.{method.Name}{generic}({Parameters(method.GetParameters())}) -> " +
               FormatType(method.ReturnType, Nullability.Create(method.ReturnParameter)) +
               Constraints(method.GetGenericArguments());
    }

    private static string Parameters(IReadOnlyList<ParameterInfo> parameters) =>
        string.Join(", ", parameters.Select(parameter =>
        {
            var prefix = parameter.GetCustomAttribute<ParamArrayAttribute>() is not null ? "params " :
                parameter.IsOut ? "out " : parameter.ParameterType.IsByRef && parameter.IsIn ? "in " :
                parameter.ParameterType.IsByRef ? "ref " : string.Empty;
            var parameterType = parameter.ParameterType.IsByRef
                ? parameter.ParameterType.GetElementType()!
                : parameter.ParameterType;
            var result = $"{prefix}{FormatType(parameterType, Nullability.Create(parameter))} {parameter.Name}";
            if (parameter.HasDefaultValue)
                result += " = " + Constant(parameter.DefaultValue, parameterType);
            return result;
        }));

    private static string TypeIdentity(Type type)
    {
        if (type.IsGenericParameter) return type.Name;
        var definition = type.IsGenericType ? type.GetGenericTypeDefinition() : type;
        var name = (definition.FullName ?? definition.Name).Replace('+', '.');
        var tick = name.IndexOf('`');
        if (tick >= 0) name = name[..tick];
        if (!type.IsGenericType) return name;
        return name + "<" + string.Join(",", type.GetGenericArguments().Select(argument => argument.Name)) + ">";
    }

    private static string FormatType(Type type, NullabilityInfo? nullability)
    {
        if (type.IsByRef) type = type.GetElementType()!;
        if (type.IsArray)
        {
            var elementNullability = nullability?.ElementType;
            var suffix = "[" + new string(',', type.GetArrayRank() - 1) + "]";
            return FormatType(type.GetElementType()!, elementNullability) + suffix + NullableSuffix(type, nullability);
        }
        if (type.IsPointer) return FormatType(type.GetElementType()!, null) + "*";
        var nullable = Nullable.GetUnderlyingType(type);
        if (nullable is not null) return FormatType(nullable, nullability?.GenericTypeArguments.FirstOrDefault()) + "?";
        if (Aliases.TryGetValue(type, out var alias)) return alias + NullableSuffix(type, nullability);
        if (type.IsGenericParameter) return type.Name + NullableSuffix(type, nullability);
        var definition = type.IsGenericType ? type.GetGenericTypeDefinition() : type;
        var name = (definition.FullName ?? definition.Name).Replace('+', '.');
        var tick = name.IndexOf('`');
        if (tick >= 0) name = name[..tick];
        if (type.IsGenericType)
        {
            var arguments = type.GetGenericArguments();
            var nullabilityArguments = nullability?.GenericTypeArguments ?? [];
            name += "<" + string.Join(",", arguments.Select((argument, index) =>
                FormatType(argument, index < nullabilityArguments.Length ? nullabilityArguments[index] : null))) + ">";
        }
        return name + NullableSuffix(type, nullability);
    }

    private static string NullableSuffix(Type type, NullabilityInfo? nullability) =>
        !type.IsValueType && nullability?.ReadState == NullabilityState.Nullable ? "?" : string.Empty;

    private static string Constraints(IEnumerable<Type> genericArguments)
    {
        var result = new StringBuilder();
        foreach (var argument in genericArguments.Where(argument => argument.IsGenericParameter))
        {
            var constraints = new List<string>();
            var attributes = argument.GenericParameterAttributes & GenericParameterAttributes.SpecialConstraintMask;
            if ((attributes & GenericParameterAttributes.ReferenceTypeConstraint) != 0) constraints.Add("class");
            if ((attributes & GenericParameterAttributes.NotNullableValueTypeConstraint) != 0) constraints.Add("struct");
            constraints.AddRange(argument.GetGenericParameterConstraints().Select(type => FormatType(type, null)));
            if ((attributes & GenericParameterAttributes.DefaultConstructorConstraint) != 0 &&
                (attributes & GenericParameterAttributes.NotNullableValueTypeConstraint) == 0)
                constraints.Add("new()");
            if (constraints.Count != 0)
                result.Append(" where ").Append(argument.Name).Append(" : ")
                    .Append(string.Join(", ", constraints));
        }
        return result.ToString();
    }

    private static string Constant(object? value, Type type)
    {
        if (value is null || value == DBNull.Value || value == Missing.Value) return "null";
        if (type.IsEnum) return $"{TypeIdentity(type)}.{Enum.GetName(type, value) ?? value.ToString()}";
        return value switch
        {
            string text => JsonEncodedText(text),
            char character => $"'{character}'",
            bool boolean => boolean ? "true" : "false",
            float number => number.ToString("R", CultureInfo.InvariantCulture) + "f",
            double number => number.ToString("R", CultureInfo.InvariantCulture),
            decimal number => number.ToString(CultureInfo.InvariantCulture) + "m",
            IFormattable formattable => formattable.ToString(null, CultureInfo.InvariantCulture),
            _ => value.ToString() ?? string.Empty,
        };
    }

    private static string JsonEncodedText(string value) =>
        "\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal) + "\"";

    private static readonly IReadOnlyDictionary<Type, string> Aliases =
        new Dictionary<Type, string>
        {
            [typeof(void)] = "void", [typeof(bool)] = "bool", [typeof(byte)] = "byte",
            [typeof(sbyte)] = "sbyte", [typeof(short)] = "short", [typeof(ushort)] = "ushort",
            [typeof(int)] = "int", [typeof(uint)] = "uint", [typeof(long)] = "long",
            [typeof(ulong)] = "ulong", [typeof(float)] = "float", [typeof(double)] = "double",
            [typeof(decimal)] = "decimal", [typeof(char)] = "char", [typeof(string)] = "string",
            [typeof(object)] = "object",
        };
}
