<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\FirstPartyWidgets\SettingsWidget\SettingsWidget.csproj" />
    <ProjectReference Include="..\..\src\WidgetProtocol\WidgetProtocol.csproj" />
    <ProjectReference Include="..\..\src\WidgetStyling\WidgetStyling.csproj" />
    <ProjectReference Include="..\..\src\PlatformBroker\PlatformBroker.csproj" />
    <ProjectReference Include="..\..\src\WidgetCatalog\WidgetCatalog.csproj" />
  </ItemGroup>
</Project>
