<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\samples\SpotifyWidget\SpotifyWidget.csproj" />
    <ProjectReference Include="..\..\src\WidgetProtocol\WidgetProtocol.csproj" />
    <ProjectReference Include="..\..\src\WidgetStyling\WidgetStyling.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\samples\SpotifyWidget\manifest.json" Link="manifest.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\samples\SpotifyWidget\styles\default.gbss" Link="styles\default.gbss" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
